// The migration run served while demo mode is on.
//
// The records come from `demo-dataset.json`, generated by
// `scripts/generate_demo_dataset.py`: a multi-source consolidation extract
// spanning four source systems of differing quality and six CI classes, with
// the full spread of reconciliation outcomes a real run produces. Regenerate
// with `npm run demo:dataset`; `npm run demo:dataset:check` fails if the
// committed file has drifted from the generator.
//
// Everything is emitted in the *raw* ServiceNow wire shape and passed through
// the real `normalizeComprehend*` adapters, so demo mode exercises the
// production normalization path rather than bypassing it. If an adapter changes,
// the demo changes with it.
//
// Three hard rules:
//   1. Deterministic. No `Math.random`, no `Date.now`. The same fixture renders
//      identically on every load, so screenshots and smoke assertions are stable.
//   2. Structurally valid. The frontend validates its own identifiers before any
//      governed action — 32-hex for run/staged-CI/finding ids, 64-hex uppercase
//      for simulation fingerprints — so ids are minted here as real hex that is
//      still obviously fake at a glance.
//   3. Never restated. Every count quoted in ledger prose or a KPI tile is
//      derived from the seeds below, and cross-checked against the generator's
//      own `summary` block by `smoke:demo-fallback`. A number that disagrees
//      with the table beneath it fails a test instead of reaching a demo.

import dataset from "./demo-dataset.json";

/** The bundled dataset, not a URL. Demo mode fetches nothing. */
export const DEMO_DATASET_NAME = dataset.dataset.name;
export const DEMO_DATASET_FILE = dataset.dataset.file;
export const DEMO_SOURCE_NAME = dataset.dataset.name;
export const DEMO_RECORD_COUNT = dataset.summary.record_count;
/** The generator's own counts, used only to assert the fixture agrees with them. */
export const DEMO_DATASET_SUMMARY = dataset.summary;
export const DEMO_SOURCE_SYSTEMS = dataset.sources;

const HEX_NAMESPACE = "deadbeefcafef00d";

/** 32-hex id: namespace + a one-char kind marker + a zero-padded index. */
function demoSysId(kind: "c" | "f" | "a" | "e" | "b" | "d", index: number): string {
  return `${HEX_NAMESPACE}${kind}${String(index).padStart(15, "0")}`;
}

/** 64-hex uppercase, matching the `simulation_fingerprint` contract. */
export function demoFingerprint(index: number): string {
  return `${HEX_NAMESPACE.toUpperCase().repeat(3)}C${String(index).padStart(15, "0")}`;
}

export const DEMO_RUN_ID = demoSysId("d", 1);

/**
 * Guard for every persistence site (URL `?run=`, run context, runs registry).
 *
 * Deliberately keyed on the *run id* rather than the demo-mode flag: when the
 * toggle flips off, effects that depend on the flag re-run while `activeRunId`
 * is still the simulated one, so a flag-based guard loses that race and leaks
 * the demo run into localStorage and the address bar. The id cannot race with
 * itself.
 */
export function isDemoRunId(runId: string | undefined | null): boolean {
  return typeof runId === "string" && runId.toLowerCase() === DEMO_RUN_ID;
}
export const DEMO_RUN_NUMBER = "DWR-DEMO-0001";
export const DEMO_RUN_LABEL = `${DEMO_SOURCE_NAME} (${DEMO_RECORD_COUNT} records)`;
/** Terminal so pipeline polling stops, but outside RUN_STATES_BLOCKING_IRE so Remediate stays reachable. */
export const DEMO_RUN_STATE = "simulated";

export const demoStagedCiId = (index: number) => demoSysId("c", index);
export const demoFindingId = (index: number) => demoSysId("f", index);
export const demoReviewId = (index: number) => demoSysId("a", index);
export const demoEventId = (index: number) => demoSysId("e", index);
export const demoTargetCiId = (index: number) => demoSysId("b", index);

// ---------------------------------------------------------------------------
// Configuration items
// ---------------------------------------------------------------------------

type DemoOperation = "INSERT" | "UPDATE" | "NO_CHANGE" | "INSERT_AS_INCOMPLETE" | "REVIEW" | "ERROR";

/**
 * The run spans six CI classes, so there is no single class constant any more.
 * These name the *largest* class in the dataset, kept for the few places that
 * need one representative label. Structured ledger evidence must carry the
 * *table* name, not the display label — `terminal-outcomes.ts` validates it
 * against /^[a-z][a-z0-9_]{2,79}$/ before a verified outcome will correlate.
 */
type DatasetCi = (typeof dataset.cis)[number];

/** Fixed base clock keeps timestamps stable across reloads. */
const BASE_DATE = "2026-07-28";
export function demoClockAt(offsetSeconds: number): string {
  return clockAt(offsetSeconds);
}
function clockAt(offsetSeconds: number): string {
  const total = 6 * 3600 + 8 * 60 + 41 + offsetSeconds;
  const hh = String(Math.floor(total / 3600) % 24).padStart(2, "0");
  const mm = String(Math.floor(total / 60) % 60).padStart(2, "0");
  const ss = String(total % 60).padStart(2, "0");
  return `${BASE_DATE} ${hh}:${mm}:${ss}`;
}

/**
 * The deterministic confidence gate. Records at or above this score have a
 * trustworthy identity; the rest are held for a human. This is an identity
 * judgement only — clearing it does not make a record eligible for autonomous
 * migration, which is a separate operation-family policy (see
 * `demoPacketCohort`).
 */
export const DEMO_GATE_THRESHOLD = dataset.dataset.gate_threshold;

export type DemoCiSeed = {
  index: number;
  sysId: string;
  name: string;
  /** Display label, e.g. "Linux Server". */
  className: string;
  /** Real CMDB table, e.g. "cmdb_ci_linux_server". */
  table: string;
  /** Source system that produced the row. */
  source: string;
  sourceId: string;
  ip: string;
  /** Support group derived from the record's class. */
  service: string;
  /** Environment or region the record belongs to. */
  region: string;
  /** The adapter's native source record key, used as the source identity. */
  sourceRecordId: string;
  operation: DemoOperation;
  confidence: number;
  /** live | review | incomplete, mirroring what the adapter will derive. */
  status: "live" | "review" | "incomplete";
  /** Index of the earlier staged row this one collapses onto, when duplicated. */
  duplicateOfIndex?: number;
  /**
   * Why this record is not in the autonomous cohort. Absent for the healthy new
   * CIs Mara may migrate on her own; every other record carries the reason the
   * operator will see in the exclusion list and on its finding.
   */
  holdReason?: string;
  /** "Linux Server|INSERT" — the homogeneous unit a bounded packet is built from. */
  workGroup: string;
};

/**
 * Rows come from the generator already classified, so this is a mapping rather
 * than a second opinion. Deriving the operation here as well would create two
 * sources of truth that could disagree — the exact failure this file exists to
 * prevent.
 */
export const demoCiSeeds: DemoCiSeed[] = (dataset.cis as DatasetCi[]).map(row => {
  const operation = row.operation as DemoOperation;
  const holdReason = (row as { hold_reason?: string }).hold_reason;
  const status = operation === "REVIEW" || operation === "ERROR"
    ? "review"
    : operation === "INSERT_AS_INCOMPLETE"
      ? "incomplete"
      : "live";
  return {
    index: row.index,
    sysId: demoStagedCiId(row.index),
    name: row.name,
    className: row.class_label,
    table: row.class_table,
    source: row.source_label,
    sourceId: row.source_id,
    ip: row.ip_address,
    service: row.support_group,
    region: row.environment,
    sourceRecordId: row.source_record_id,
    operation,
    confidence: row.confidence,
    status,
    ...(typeof (row as { duplicate_of_index?: number }).duplicate_of_index === "number"
      ? { duplicateOfIndex: (row as { duplicate_of_index?: number }).duplicate_of_index }
      : {}),
    ...(holdReason ? { holdReason } : {}),
    workGroup: `${row.class_label}|${operation}`,
  } satisfies DemoCiSeed;
});

export const DEMO_CI_COUNT = demoCiSeeds.length;

function ciNameFor(index: number): string {
  return demoCiSeeds[index]?.name ?? `staged-record-${index + 1}`;
}

// ---------------------------------------------------------------------------
// Counts. Every number the UI or the ledger prose quotes is measured here, once,
// from the seeds above — nothing downstream is allowed to restate one by hand.
// `smoke:demo-fallback` asserts each of these equals the generator's own count.
// ---------------------------------------------------------------------------

const countOf = (operation: DemoOperation) => demoCiSeeds.filter(seed => seed.operation === operation).length;

/** Cleared the identity gate. Includes matched records, which are not autonomous. */
const clearedCount = demoCiSeeds.filter(seed => seed.confidence >= DEMO_GATE_THRESHOLD).length;
const heldCount = DEMO_CI_COUNT - clearedCount;
const duplicateCandidateCount = countOf("REVIEW");
const incompleteCount = countOf("INSERT_AS_INCOMPLETE");
const matchedCount = countOf("UPDATE") + countOf("NO_CHANGE");
const errorCount = countOf("ERROR");
const distinctIdentityCount = DEMO_CI_COUNT - duplicateCandidateCount;
const sourceCount = dataset.sources.length;
const classCount = dataset.classes.length;

const autonomousSeeds = demoCiSeeds.filter(seed => !seed.holdReason);
const autonomousCount = autonomousSeeds.length;

/** The largest class in the run, for the few places that need one label. */
const dominantClass = [...demoCiSeeds].reduce<Record<string, number>>((acc, seed) => {
  acc[seed.table] = (acc[seed.table] ?? 0) + 1;
  return acc;
}, {});
export const DEMO_CLASS_TABLE = Object.entries(dominantClass).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "cmdb_ci";
export const DEMO_CLASS_LABEL = demoCiSeeds.find(seed => seed.table === DEMO_CLASS_TABLE)?.className ?? "Configuration Item";

const pct = (value: number) => `${Math.round(value * 100)}%`;
const clearedConfidences = demoCiSeeds.filter(seed => seed.confidence >= DEMO_GATE_THRESHOLD).map(seed => seed.confidence);
const clearedScoreRange = clearedConfidences.length
  ? `${pct(Math.min(...clearedConfidences))} to ${pct(Math.max(...clearedConfidences))}`
  : "n/a";
const heldScoreCeiling = pct(Math.max(...demoCiSeeds.map(s => s.confidence).filter(value => value < DEMO_GATE_THRESHOLD), 0));

export function demoCisPayload() {
  return {
    result: demoCiSeeds.map(seed => ({
      sys_id: seed.sysId,
      number: `DCI${String(10000 + seed.index)}`,
      display_name: seed.name,
      proposed_class: seed.className,
      source_name: seed.source,
      ip_address: seed.ip,
      operation: seed.operation,
      confidence: seed.confidence,
      class_valid: seed.status === "live",
      identification_status: seed.status === "live" ? "identified" : "requires_review",
      migration_run: { value: DEMO_RUN_ID, display_value: DEMO_RUN_NUMBER },
      ...(seed.operation === "UPDATE"
        ? { matched_ci: { value: demoTargetCiId(seed.index), display_value: seed.name } }
        : {}),
      source_identity: {
        source_name: seed.source,
        source_record_id: seed.sourceRecordId,
      },
      sys_updated_on: clockAt(seed.index * 3),
    })),
  };
}

// ---------------------------------------------------------------------------
// Event ledger
// ---------------------------------------------------------------------------

type DemoEventSeed = {
  eventType: string;
  actor?: string;
  detail: string;
  status?: "complete" | "active" | "review" | "error";
  recordName?: string;
};

/**
 * Compact analysis-only replay of the ServiceNow-owned Mara loop. Lifecycle
 * evidence is appended later by the demo transport when the operator actually
 * starts simulation and packet execution.
 */
// Relationship counts are resolved after the graph below is initialized.
const relationshipTouched = new Set<number>();

const EVENT_SEEDS: DemoEventSeed[] = [
  {
    eventType: "ingested",
    actor: "Comprehend",
    detail: `Source received: ${DEMO_CI_COUNT} rows from ${DEMO_DATASET_FILE} entered quarantine across ${sourceCount} source systems. Every row landed in the staging tables only; no CMDB table was read or written.`,
  },
  {
    eventType: "analyzed",
    actor: "Mara",
    detail: "Thought: Establish the run boundary and prove every row belongs to this migration before specialist analysis. | Action: get_run_stats",
  },
  {
    eventType: "record_staged",
    actor: "Router",
    detail: `Result: ${DEMO_CI_COUNT} rows are quarantined in staging under one run, tagged to ${sourceCount} source systems. Required keys are present on every row; raw values are retained verbatim and remain replayable.`,
  },
  {
    eventType: "analyzed",
    actor: "Mara",
    detail: "Handoff: Mara -> Atlas | Action: scan_classes",
  },
  {
    eventType: "analyzed",
    actor: "Atlas",
    detail: `Result: ${DEMO_CI_COUNT} records propose ${classCount} allowlisted CI classes, led by ${DEMO_CLASS_LABEL}; no caller-supplied class or executable payload was accepted. ${errorCount} collide with an existing CI of a different class and cannot be reconciled.`,
  },
  {
    eventType: "analyzed",
    actor: "Mara",
    detail: "Handoff: Mara -> Atlas | Action: scan_attributes",
  },
  {
    eventType: "analyzed",
    actor: "Atlas",
    detail: `Result: Host, address, environment, and ownership columns mapped onto identity, environment, support-group, and provenance evidence across all ${classCount} classes. ${incompleteCount} records are missing a required attribute and would land without a resolvable owner.`,
  },
  {
    eventType: "analyzed",
    actor: "Mara",
    detail: "Handoff: Mara -> Scout | Action: scan_duplicates",
  },
  {
    eventType: "analyzed",
    actor: "Scout",
    detail: `Result: ${DEMO_CI_COUNT} staged rows collapse onto ${distinctIdentityCount} distinct identities. ${duplicateCandidateCount} rows match an identity another source already staged — the same asset seen by two scanners — so each pair needs a human to pick the surviving record.`,
  },
  {
    eventType: "analyzed",
    actor: "Mara",
    detail: "Handoff: Mara -> Weaver | Action: scan_orphans",
  },
  {
    eventType: "analyzed",
    actor: "Weaver",
    detail: "Result: RELATIONSHIP_COUNT dependency edges discovered between staged records — applications to their hosts, databases to their servers, hosts to their networks. ORPHAN_COUNT records have no staged edge. Relationships stay blocked until both endpoints verify.",
  },
  {
    eventType: "analyzed",
    actor: "Mara",
    detail: "Handoff: Mara -> Guard | Action: apply_confidence_gate",
  },
  {
    eventType: "analyzed",
    actor: "Sentry",
    detail: `Result: Confidence gate applied at ${pct(DEMO_GATE_THRESHOLD)}. ${clearedCount} records cleared, scoring ${clearedScoreRange}; ${heldCount} were held at or below ${heldScoreCeiling} and stay for human review.`,
  },
  {
    eventType: "analyzed",
    actor: "Mara",
    detail: `Observation: Of the ${clearedCount} cleared records, ${matchedCount} match an existing CI and are outside the autonomous boundary. ${autonomousCount} healthy unmatched insertion candidates remain; simulation is the next safe non-mutating action.`,
  },
  {
    eventType: "analyzed",
    actor: "Mara",
    detail: "Handoff: Mara -> Prioritize | Action: rank_health_opportunities",
  },
  {
    eventType: "analyzed",
    actor: "Prioritize",
    detail: `Result: WORK_GROUP_COUNT approvable work groups derived, and four quality opportunities ranked by the health each returns: duplicate resolution, ownership metadata, relationship coverage, and class conflicts. Migration eligibility stays separate from that improvement backlog.`,
  },
  {
    eventType: "analyzed",
    actor: "Mara",
    detail: "Thought: Preserve the specialist evidence, expose the remaining quality backlog, and stop before IRE simulation. | Action: write_summary",
  },
  {
    eventType: "analyzed",
    actor: "Ledger",
    detail: `Result: Analysis completed. W-R-A-G-S evidence is sealed for ${DEMO_CI_COUNT} staged CIs: ${autonomousCount} are ready for governed simulation, ${DEMO_CI_COUNT - autonomousCount} await an operator decision (${duplicateCandidateCount} duplicate, ${incompleteCount} incomplete, ${matchedCount} matched, ${errorCount} unreconcilable). No CMDB mutation has started.`,
  },
];

/**
 * How much of the ledger each pipeline stage exposes while the simulated run
 * progresses after an import:
 *   stage 0 - intake and run boundary
 *   stage 1 - Atlas, Scout, and Weaver outputs
 *   stage 2 - Guard gate and Mara decision
 *   stage 3 - Prioritize and Ledger seal
 */
export const DEMO_STAGE_EVENT_COUNTS = [3, 11, 14, EVENT_SEEDS.length] as const;

export function demoTimelinePayload(limit = EVENT_SEEDS.length) {
  return {
    result: EVENT_SEEDS.slice(0, Math.max(0, limit)).map((seed, index) => ({
      sys_id: demoEventId(index + 1),
      sequence: index + 1,
      event_type: seed.eventType,
      ...(seed.actor ? { agent: seed.actor } : {}),
      ...(seed.recordName ? { staged_ci: { display_value: seed.recordName } } : {}),
      ...(seed.status ? { status: seed.status } : {}),
      detail: seed.detail
        .replace("RELATIONSHIP_COUNT", String(RELATIONSHIP_ROWS.length))
        .replace("WORK_GROUP_COUNT", String(demoWorkGroups.length))
        .replace("ORPHAN_COUNT", String(DEMO_CI_COUNT - relationshipTouched.size)),
      sys_created_on: clockAt(index * 4),
    })),
  };
}

// ---------------------------------------------------------------------------
// Relationships
// ---------------------------------------------------------------------------

// Edges are generated alongside the CIs so both endpoints are guaranteed to
// exist and to be records the run can actually promote — the generator only
// links non-held CIs, because a relationship whose endpoint is still awaiting a
// human decision could never land anyway.
const RELATIONSHIP_ROWS = dataset.relationships;
for (const edge of RELATIONSHIP_ROWS) {
  relationshipTouched.add(edge.parent_index);
  relationshipTouched.add(edge.child_index);
}

export function demoRelationshipsPayload() {
  return {
    result: RELATIONSHIP_ROWS.map((edge, index) => ({
      sys_id: demoSysId("e", 500 + index),
      parent_ci: { value: demoStagedCiId(edge.parent_index), display_value: ciNameFor(edge.parent_index) },
      child_ci: { value: demoStagedCiId(edge.child_index), display_value: ciNameFor(edge.child_index) },
      relationship_type: edge.type,
      confidence: edge.confidence,
    })),
  };
}

// ---------------------------------------------------------------------------
// Findings and review decisions
// ---------------------------------------------------------------------------

type DemoFindingSeed = {
  ciIndex: number;
  type: string;
  severity: "critical" | "high" | "medium";
  recommendation: string;
  decision: "deferred" | "approved" | "rejected";
  rationale: string;
};

/**
 * Findings link to CIs by `staged_ci`, and reviews link to findings by
 * `finding`. If those references do not resolve, `deriveRemediationWorkQueue`
 * classifies every row as `derived_staging` and the Remediate and Approvals
 * views render empty — so the cross-referencing here is load-bearing.
 */
/**
 * The autonomous cohort: healthy, unmatched, gate-cleared new networks, all in
 * one class and one operation family. The transport slices it into
 * policy-compliant packets of 100 and child campaigns of 20.
 *
 * Deliberately narrower than "everything that cleared the gate". Matched
 * UPDATEs score well above the threshold but are still excluded, because the
 * autonomous boundary is about the *operation* — Mara may create a new CI on
 * her own, and may never change an existing one. Everything outside this list
 * carries a `holdReason` and stays for the operator.
 */
export const demoPacketCohort: DemoCiSeed[] = autonomousSeeds;
export const DEMO_AUTONOMOUS_COUNT = autonomousCount;
export const DEMO_HELD_FOR_REVIEW_COUNT = DEMO_CI_COUNT - autonomousCount;

export type DemoWorkGroup = {
  /** "Linux Server|INSERT" — what the campaign API calls a work group signature. */
  signature: string;
  classLabel: string;
  classTable: string;
  operation: DemoOperation;
  title: string;
  seeds: DemoCiSeed[];
};

/**
 * The autonomous cohort split into homogeneous work groups.
 *
 * A bounded approval packet must be homogeneous — one class, one operation —
 * so with six classes in the run the cohort can no longer be sliced as a flat
 * list. Each group is a separately approvable unit, which is also what makes
 * Prioritize meaningful: the operator sees which group buys the most health per
 * approval rather than one undifferentiated pile of 384 records.
 *
 * Ordered largest-first so the highest-impact group leads the ranked list.
 */
export const demoWorkGroups: DemoWorkGroup[] = (() => {
  const groups = new Map<string, DemoWorkGroup>();
  for (const seed of autonomousSeeds) {
    const existing = groups.get(seed.workGroup);
    if (existing) { existing.seeds.push(seed); continue; }
    groups.set(seed.workGroup, {
      signature: seed.workGroup,
      classLabel: seed.className,
      classTable: seed.table,
      operation: seed.operation,
      title: `Healthy new ${seed.className} records`,
      seeds: [seed],
    });
  }
  return [...groups.values()].sort((a, b) => b.seeds.length - a.seeds.length || a.signature.localeCompare(b.signature));
})();

export const DEMO_PACKET_SIZE = 100;
export const DEMO_CAMPAIGN_SIZE = 20;

/**
 * Every staged CI gets a finding and a review decision — not just the held
 * records and the packet cohort.
 *
 * This is load-bearing for the Remediate workbench, not cosmetic. "Commit this
 * CI to ServiceNow" is gated on `approvable`, which requires BOTH
 * `selectedQueueItem.finding?.id` and `.review?.id`. A record with no finding
 * can be simulated but can never be committed, so the button sits permanently
 * greyed out with no way for the operator to discover why. Covering every
 * record is also the truthful shape: Comprehend raises a finding for each
 * record it proposes an action on.
 */
const FINDING_TYPE: Record<DemoOperation, string> = {
  INSERT: "reconciliation_candidate",
  UPDATE: "existing_ci_match",
  REVIEW: "duplicate_identity",
  INSERT_AS_INCOMPLETE: "incomplete_attributes",
  ERROR: "class_conflict",
  NO_CHANGE: "no_change",
};

export const demoFindingSeeds: DemoFindingSeed[] = demoCiSeeds.map(seed => ({
  ciIndex: seed.index,
  type: FINDING_TYPE[seed.operation],
  severity: seed.operation === "ERROR"
    ? "critical"
    : seed.holdReason ? "high" : "medium",
  // The recommendation states the action the record is actually a candidate
  // for, so an operator reading the finding is not told to create something
  // that IRE has already refused to reconcile.
  recommendation: seed.holdReason
    ? `Resolve before migrating: ${seed.holdReason}`
    : `Create ${seed.name} in the CMDB as a governed ${seed.operation} once its simulation is approved.`,
  decision: "deferred",
  rationale: seed.holdReason
    ? "Held for an operator decision. No governed action is proposed until the blocking condition is resolved."
    : "Identity evidence is sufficient and awaits authorization through a bounded approval packet.",
} satisfies DemoFindingSeed));

export function demoFindingsPayload() {
  return {
    result: demoFindingSeeds.map((seed, index) => ({
      sys_id: demoFindingId(seed.ciIndex),
      number: `DWF${String(2000 + index)}`,
      staged_ci: { value: demoStagedCiId(seed.ciIndex), display_value: ciNameFor(seed.ciIndex) },
      type: seed.type,
      severity: seed.severity,
      recommendation: seed.recommendation,
    })),
  };
}

export function demoReviewsPayload() {
  return {
    result: demoFindingSeeds.map((seed, index) => ({
      sys_id: demoReviewId(seed.ciIndex),
      finding: { value: demoFindingId(seed.ciIndex), display_value: `DWF${String(2000 + index)}` },
      decision: seed.decision,
      rationale: seed.rationale,
      policy_approved: seed.decision === "approved",
    })),
  };
}

// ---------------------------------------------------------------------------
// Health
// ---------------------------------------------------------------------------

/**
 * Every quantity below is measured off the seeds and the relationship graph.
 * The dimension scores are the share of records that actually satisfy each
 * property, so a KPI tile can never contradict the table beneath it:
 *
 *   completeness — has every required attribute (not INSERT_AS_INCOMPLETE)
 *   correctness  — reconciles to exactly one identity (not REVIEW or ERROR)
 *   compliance   — cleared the deterministic confidence gate
 */
const share = (matching: number) => Math.round((matching / DEMO_CI_COUNT) * 100);
const completenessScore = share(DEMO_CI_COUNT - incompleteCount);
const correctnessScore = share(DEMO_CI_COUNT - duplicateCandidateCount - errorCount);
const complianceScore = share(clearedCount);

/**
 * The health scale has two fixed endpoints and a live reading between them.
 *
 *   baseline  — the staged data as it arrived, averaged across the three
 *               dimensions above
 *   projected — where the CMDB lands once everything resolvable is resolved,
 *               short of 100 by the class conflicts this pipeline will never
 *               decide on its own
 *
 * The reading in between is *not* a stored constant. It is computed from how
 * many records have actually reached correlated verification, so the score
 * moves while remediation runs. A fixed middle value is exactly what made the
 * projected score sit still through a whole migration.
 */
const baselineScore = Math.round((completenessScore + correctnessScore + complianceScore) / 3);
const projectedScore = Math.floor(((DEMO_CI_COUNT - errorCount) / DEMO_CI_COUNT) * 100);
const totalLift = Math.max(0, projectedScore - baselineScore);

/** Records absent from recent source publications — a CMDB-side observation. */
const notObservedRecently = (index: number) => index % 53 === 11;
const staleCount = demoCiSeeds.filter(seed => notObservedRecently(seed.index)).length;

/**
 * Split the *remaining* lift across the four ranked fixes so their impacts sum
 * to exactly `projected - current`.
 *
 * Prioritize adds these up for its "% AVAILABLE" tile and renders
 * "move the estate from {current} to a projected {current + available}". Static
 * impacts therefore re-promise lift that migration has already delivered — the
 * panel read "from 94 to a projected 100" once the cohort landed, overshooting
 * the real ceiling of 97. Recomputing against the current score keeps the two
 * numbers consistent at every point in the run, and drains to zero at the
 * ceiling, where Prioritize switches to "HEALTH AT MAXIMUM".
 *
 * Weighted by how many records each fix would unblock; the rounding remainder
 * goes to rank 1.
 */
function fixImpactsFor(currentScore: number): number[] {
  const remaining = Math.max(0, projectedScore - currentScore);
  const weights = [duplicateCandidateCount, incompleteCount, errorCount, errorCount];
  const total = weights.reduce((a, b) => a + b, 0) || 1;
  const shares = weights.map(w => Math.floor((remaining * w) / total));
  shares[0] += remaining - shares.reduce((a, b) => a + b, 0);
  return shares;
}

/** Health earned so far, given how many records are verified in the CMDB. */
export function demoHealthScoreAt(verifiedCount: number): number {
  const progress = DEMO_CI_COUNT ? Math.min(1, Math.max(0, verifiedCount / DEMO_CI_COUNT)) : 0;
  return baselineScore + Math.round(totalLift * progress);
}

/**
 * Per-work-group health impact.
 *
 * `projected` is that group's share of the total available lift, so the ranked
 * list answers the question Prioritize is for — which approval buys the most
 * health. `realized` is the part already earned, so a group's contribution
 * fills in as its records verify rather than flipping at the end.
 */
function workGroupImpacts(verifiedIds: ReadonlySet<string>) {
  return demoWorkGroups.map(group => {
    const verified = group.seeds.filter(seed => verifiedIds.has(seed.sysId)).length;
    const projected = Number((totalLift * (group.seeds.length / DEMO_CI_COUNT)).toFixed(2));
    return {
      signature: group.signature,
      title: group.title,
      projected,
      realized: Number((projected * (group.seeds.length ? verified / group.seeds.length : 0)).toFixed(2)),
      affected: group.seeds.length,
      staged_ci_ids: group.seeds.slice(0, 20).map(seed => seed.sysId),
    };
  });
}

/**
 * @param verifiedIds staged CI ids with correlated verification evidence. The
 *   transport passes its live set; callers with no run progress pass nothing
 *   and get the baseline reading.
 */
export function demoHealthPayload(verifiedIds: ReadonlySet<string> = new Set()) {
  const orphanCount = DEMO_CI_COUNT - relationshipTouched.size;
  const score = demoHealthScoreAt(verifiedIds.size);
  const fixImpacts = fixImpactsFor(score);
  return {
    result: {
      score,
      grade: score >= 90 ? "A" : score >= 80 ? "B" : score >= 70 ? "C" : "D",
      baseline_score: baselineScore,
      verified_score: score,
      projected_score: projectedScore,
      ci_count: DEMO_CI_COUNT,
      duplicates_detected: duplicateCandidateCount,
      review_count: DEMO_HELD_FOR_REVIEW_COUNT,
      relationship_count: RELATIONSHIP_ROWS.length,
      completeness: completenessScore,
      correctness: correctnessScore,
      compliance: complianceScore,
      duplicate_rate: Number(((duplicateCandidateCount / DEMO_CI_COUNT) * 100).toFixed(1)),
      stale_records: staleCount,
      work_group_impacts: workGroupImpacts(verifiedIds),
      // Impacts must sum to exactly the lift the projection promises, or
      // Prioritize's "% AVAILABLE" tile contradicts the projected score.
      // Ranked by the health each one buys back. Every `affected` count is a
      // measured population, so the list cannot promise work that does not exist.
      fixes: [
        {
          id: "FIX-01", rank: 1, title: "Resolve duplicate identities across sources",
          description: `${duplicateCandidateCount} records reconcile to an identity another source already staged. Each pair needs one surviving record before either can be created.`,
          impact: fixImpacts[0], affected: duplicateCandidateCount, tool: "Scout", severity: "high",
        },
        {
          id: "FIX-02", rank: 2, title: "Complete missing ownership metadata",
          description: `${incompleteCount} records are missing a required attribute, so they would land in the CMDB without a resolvable owner.`,
          impact: fixImpacts[1], affected: incompleteCount, tool: "Guard", severity: "high",
        },
        {
          id: "FIX-03", rank: 3, title: "Increase relationship coverage",
          description: `${orphanCount} records have no staged relationship. Dependencies can be discovered once their endpoints exist in the CMDB.`,
          impact: fixImpacts[2], affected: orphanCount, tool: "Weaver", severity: "medium",
        },
        {
          id: "FIX-04", rank: 4, title: "Resolve class conflicts",
          description: `${errorCount} records already exist under a different class. IRE cannot reconcile a class change, so each needs an explicit decision.`,
          impact: fixImpacts[3], affected: errorCount, tool: "Atlas", severity: "medium",
        },
      ],
    },
  };
}

// ---------------------------------------------------------------------------
// Run record, instance, and AI usage
// ---------------------------------------------------------------------------

export function demoRunPayload(state: string = DEMO_RUN_STATE) {
  return {
    result: {
      sys_id: DEMO_RUN_ID,
      number: DEMO_RUN_NUMBER,
      state,
      source_system: DEMO_DATASET_FILE,
      started: clockAt(0),
      summary: DEMO_RUN_LABEL,
    },
  };
}

/**
 * Deliberately reports no host. Demo mode is not pretending to be connected to
 * an instance, so there is nothing to name — the demo toggle is the only signal
 * the header needs.
 */
export function demoInstancePayload() {
  return {};
}

const USAGE_SEEDS: Array<[string, string, number, number, number, string]> = [
  ["Comprehend", "claude-opus-5", 4820, 940, 3120, "success"],
  ["Comprehend", "claude-opus-5", 3610, 720, 2480, "success"],
  ["Comprehend", "claude-opus-5", 5140, 1180, 3890, "success"],
  ["Mara", "claude-opus-5", 6210, 1640, 4510, "success"],
  ["Mara", "claude-opus-5", 2980, 610, 1970, "success"],
  // At least one deterministic-fallback call so the AI Usage page's fallback
  // banner is exercised rather than sitting untested behind a happy path.
  ["Mara", "deterministic", 0, 0, 140, "fallback"],
  ["Prioritize", "claude-opus-5", 3340, 880, 2610, "success"],
  ["Prioritize", "claude-opus-5", 2110, 470, 1580, "success"],
];

export function demoUsagePayload() {
  return {
    result: {
      run_id: DEMO_RUN_ID,
      calls: USAGE_SEEDS.map(([phase, model, input, output, duration, status], index) => ({
        sys_id: demoSysId("e", 900 + index),
        sys_created_on: clockAt(index * 11),
        phase,
        model,
        input_tokens: input,
        output_tokens: output,
        total_tokens: input + output,
        duration_ms: duration,
        status,
      })),
    },
  };
}
